// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package extension_base is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	BaseMessage
	OldStyleMessage
*/
package pb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type BaseMessage struct {
	Height           *int32                    `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *BaseMessage) Reset()         { *m = BaseMessage{} }
func (m *BaseMessage) String() string { return proto.CompactTextString(m) }
func (*BaseMessage) ProtoMessage()    {}

var extRange_BaseMessage = []proto.ExtensionRange{
	{4, 9},
	{16, 536870911},
}

func (*BaseMessage) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_BaseMessage
}
func (m *BaseMessage) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *BaseMessage) GetHeight() int32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

// Another message that may be extended, using message_set_wire_format.
type OldStyleMessage struct {
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *OldStyleMessage) Reset()         { *m = OldStyleMessage{} }
func (m *OldStyleMessage) String() string { return proto.CompactTextString(m) }
func (*OldStyleMessage) ProtoMessage()    {}

func (m *OldStyleMessage) Marshal() ([]byte, error) {
	return proto.MarshalMessageSet(m.ExtensionMap())
}
func (m *OldStyleMessage) Unmarshal(buf []byte) error {
	return proto.UnmarshalMessageSet(buf, m.ExtensionMap())
}

// ensure OldStyleMessage satisfies proto.Marshaler and proto.Unmarshaler
var _ proto.Marshaler = (*OldStyleMessage)(nil)
var _ proto.Unmarshaler = (*OldStyleMessage)(nil)

var extRange_OldStyleMessage = []proto.ExtensionRange{
	{100, 2147483646},
}

func (*OldStyleMessage) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_OldStyleMessage
}
func (m *OldStyleMessage) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func init() {
}
